ALL: rotate enterexit ledmeter

rotate: rotate.c
	gcc -o rotate rotate.c

enterexit: enterexit.c
	gcc -o enterexit enterexit.c

ledmeter: ledmeter.c
	gcc -o ledmeter ledmeter.c

clean:
	rm rotate enterexit ledmeter
